blueprint: 
  name: Remotec ZRC90
  description: Automate your Remotec ZRC90 8 button Remote
  domain: automation
  source_url: https://raw.githubusercontent.com/tchoward/Home-Assistant/main/Remotec_ZRC_90_blueprint.yaml
  input:
    remote:
      name: Remotec ZRC-90
      selector:
        device:
          integration: hubitat     
    button_1_single:
      name: Button 1 (single press)
      default: []
      selector:
        action: {}
    button_1_double:
      name: Button 1 (double press)
      default: []
      selector:
        action: {}
    button_1_hold:
      name: Button 1 (long press)
      default: []
      selector:
        action: {}
        
mode: restart
max_exceeded: silent

trigger:
- platform: state
  device_id: !input 'remote'
  from: ""

condition:
- condition: template
  value_template: "{{ 'button' in trigger.to_state.state }}"

action:
- variables:
    command: '{{ trigger.to_state.attributes.action }}'
- choose:
  - conditions:
    - '{{ command == "button_1_single" }}'
    sequence: !input 'button_1_single'
  - conditions:
    - '{{ command == "button_1_double" }}'
    sequence: !input 'button_1_double'
  - conditions:
    - '{{ command == "button_1_hold" }}'
    sequence:
    - repeat:
        until:
        - condition: state
          entity_id: !input 'remote'
          state: button_1_release
          attribute: action
        sequence: !input 'button_1_hold'
  
