blueprint:
  name: Remotec ZRC-90 Scene Master
  description: Create an automation for the Remotec ZRC-90 8 button remote using ZWAVE-JS integration
  domain: automation
  input:
    remotec_zrc90:
      name: Remotec ZRC-90
      description: The Remotec ZRC-90 to interact with.
      selector:
        device:
          model: Remotec ZRC-90
    button_1_1:
      name: Press Button One 1x
      description: Action to run on button press once.
      default: []
      selector:
        action: {}
mode: single

max_exceeded: silent

trigger:
  platform: event
  event_type: zwave_js_value_notification
  event_data:
    command_class_name: Central Scene
    device_id: !input remotec_zrc90
action:
  - variables:
      scene_id: "{{ trigger.event.data.property_key_name }}"
      scene_value_id: "{{ trigger.event.data.value }}"

  - choose:
      - conditions: "{{ scene_id == '001' and scene_value_id == 'KeyPressed' }}"
        sequence: !input button_1_1
